### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoClassDefFoundError: com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser$Feature

### ISSUE THREAD

**Issue by Jaxon-Wei** [CUTR-at-USF/cutr-mvn-repo#2]
@barbeau  hello, tks for your work, your wiki "Parsing JSON and XML on Android" is very helpful for me。Use your code, my app work well. But, when i update my dependency to next:

```
compile 'com.fasterxml.jackson.core:jackson-core:2.6.7'
compile 'com.fasterxml.jackson.core:jackson-annotations:2.6.7'
compile 'com.fasterxml.jackson.core:jackson-databind:2.6.7'
// Repackaged XML-specific libraries
compile 'edu.usf.cutr.android.xml:jackson-dataformat-xml-android:2.6.2'
compile 'edu.usf.cutr.android.xml:stax2-api-android:4.0.0'
compile 'edu.usf.cutr.android.xml:stax-api-android:1.0-2'
compile 'edu.usf.cutr.android.xml:aalto-xml-android:0.9.10'`
```

I encountered this error in my project:

`java.lang.RuntimeException: java.lang.NoClassDefFoundError: com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser$Feature`

and here is my code:

`XmlMapper xmlMapper = new XmlMapper(new XmlFactory(new InputFactoryImpl(), new OutputFactoryImpl()), new JacksonXmlModule());`

what is wrong? thank you

**Comment by barbeau** [comment]
The `jackson-dataformat-xml-android` version needs to match the other `jackson.core` library versions.  I don't believe we've generated higher than 2.6.2 yet, but you're welcome to generate them yourselves if you need them.  See https://github.com/CUTR-at-USF/SiriRestClient/wiki/Modifying-XML-libraries-for-Android for instructions.
